version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: my_ctf_web
    ports:
      - "49200:80"  # Actual service is now hidden on port 49200
    volumes:
      - ./uploads:/app/uploads
      - ./profile_photo:/app/profile_photo
    restart: unless-stopped
    
  ghost_admin:
    build:
      context: ./ghost_admin
      dockerfile: Dockerfile
    container_name: ghost_admin
    depends_on:
      - web
    restart: unless-stopped
    
  decoy_ports:
    build:
      context: ./decoy_ports
      dockerfile: Dockerfile
    container_name: decoy_ports
    ports:
      - "21:21"     # FTP decoy
      - "22:22"     # SSH decoy
      - "80:80"     # HTTP decoy (login panel)
      - "443:443"   # HTTPS decoy
      - "3306:3306" # MySQL decoy
      - "8080:8080" # Web app decoy
    restart: unless-stopped