version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: my_ctf_web
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped