version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: my_ctf_web
    ports:
      - "80:80"
    volumes:
      - ./uploads:/app/uploads
      - ./profile_photo:/app/profile_photo
    restart: unless-stopped

  ghost_admin:
    build:
      context: ./ghost_admin
      dockerfile: Dockerfile
    container_name: ghost_admin
    depends_on:
      - web
    restart: unless-stopped

  decoy:
    image: alpine:latest
    container_name: decoy_ports
    command: >
      sh -c "
        apk add --no-cache socat &&
        echo 'OK IMAP4 ready' | socat TCP-LISTEN:143,fork -
        & echo 'HTTP/1.1 200 OK\r\n\r\nFake Web Server' | socat TCP-LISTEN:8000,fork -
      "
    ports:
      - "143:143"
      - "8000:8000"
    restart: unless-stopped
